#!/usr/bin/env bash
# 文档指纹机制：清单生成/校验 + 版本指纹 + 版本变更清单 + 历史版本复核 + 打版本标签
# 受管范围：所有 *.md + scripts/*.sh + .github/**/*.yml + infra/**/*.yml
# 版本模型：tag → commit → MANIFEST.sha256 → 单文件 SHA256（逐层可校验）
# 用法：
#   bash scripts/doc-fingerprint.sh generate          # 重新生成清单（与文件变更同一提交）
#   bash scripts/doc-fingerprint.sh verify            # 校验工作区与清单一致（体检/CI 自动调用）
#   bash scripts/doc-fingerprint.sh id                # 输出当前版本指纹（集合 SHA256 前 12 位）
#   bash scripts/doc-fingerprint.sh changes <ref>     # 对比任意版本(tag/commit)与当前的文件级变更
#   bash scripts/doc-fingerprint.sh verify-ref <ref>  # 复核任意历史版本的完整性
#   bash scripts/doc-fingerprint.sh tag <name>        # 校验通过后打内嵌版本指纹的附注标签
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1
MANIFEST="MANIFEST.sha256"

files() {
  {
    find . -name '*.md' -not -path './.git/*'
    find scripts .github infra -type f \( -name '*.sh' -o -name '*.yml' \) 2>/dev/null
  } | sed 's#^\./##' | LC_ALL=C sort
}

# 当前所有受管文件的 "路径 指纹" 列表（按路径排序）
hashes_now() {
  files | while read -r f; do sha256sum "$f" | sed -E 's/^([0-9a-f]{64})  (.*)$/\2 \1/'; done | LC_ALL=C sort
}

case "${1:-verify}" in
  generate)
    files | while read -r f; do sha256sum "$f"; done > "$MANIFEST.tmp"
    mv "$MANIFEST.tmp" "$MANIFEST"
    echo "清单已生成：$MANIFEST（$(wc -l < "$MANIFEST") 个文件）。请与本次文件变更放在同一提交里。"
    ;;
  verify)
    if [ ! -f "$MANIFEST" ]; then echo "  [错误] 清单不存在，先运行 generate"; exit 1; fi
    if sha256sum -c "$MANIFEST" --quiet 2>/dev/null; then
      echo "  指纹校验通过（$(wc -l < "$MANIFEST") 个文件与清单一致）"
      exit 0
    fi
    echo "  [指纹不一致] 以下文件与清单不符（被修改但未重新生成清单，或被篡改）："
    sha256sum -c "$MANIFEST" 2>/dev/null | grep -v ': OK$' | sed 's/^/    /' || true
    comm -13 <(cut -d' ' -f3- "$MANIFEST" | LC_ALL=C sort) <(files) | sed 's/^/    [清单外新文件] /'
    exit 1
    ;;
  id)
    [ -f "$MANIFEST" ] || { echo "清单不存在，先 generate"; exit 1; }
    echo "版本指纹(set-fingerprint): $(sha256sum "$MANIFEST" | cut -c1-12)"
    echo "受管文件数: $(wc -l < "$MANIFEST")"
    echo "当前提交: $(git rev-parse --short HEAD 2>/dev/null || echo 未提交)"
    echo "最近标签: $(git describe --tags --abbrev=0 2>/dev/null || echo 无)"
    ;;
  changes)
    ref="${2:?用法: changes <ref>（tag 或 commit）}"
    git cat-file -e "$ref:MANIFEST.sha256" 2>/dev/null || { echo "[错误] $ref 上没有清单"; exit 1; }
    tmp=$(mktemp -d)
    git show "$ref:MANIFEST.sha256" | sed -E 's/^([0-9a-f]{64})  (.*)$/\2 \1/' | LC_ALL=C sort > "$tmp/old"
    hashes_now > "$tmp/new"
    echo "== 相对版本 $ref 的文件级变更 =="
    join "$tmp/old" "$tmp/new" 2>/dev/null | awk '$2!=$3 {print "  [修改] " $1}'
    comm -13 <(cut -d' ' -f1 "$tmp/old") <(cut -d' ' -f1 "$tmp/new") | sed 's/^/  [新增] /'
    comm -23 <(cut -d' ' -f1 "$tmp/old") <(cut -d' ' -f1 "$tmp/new") | sed 's/^/  [删除] /'
    rm -rf "$tmp"
    ;;
  verify-ref)
    ref="${2:?用法: verify-ref <ref>（tag 或 commit）}"
    git cat-file -e "$ref:MANIFEST.sha256" 2>/dev/null || { echo "[错误] $ref 上没有清单"; exit 1; }
    tmp=$(mktemp -d)
    git archive "$ref" | tar -x -C "$tmp"
    if (cd "$tmp" && sha256sum -c MANIFEST.sha256 --quiet 2>/dev/null); then
      echo "  版本 $ref 完整性复核通过（该版本全部文件与其清单一致）"
      rc=0
    else
      echo "  [失败] 版本 $ref 存在与清单不一致的文件"
      rc=1
    fi
    rm -rf "$tmp"
    exit $rc
    ;;
  tag)
    name="${2:?用法: tag <name>（如 archive-2026-10）}"
    bash "$0" verify >/dev/null || { echo "[错误] 清单校验未通过，禁止打标签"; exit 1; }
    fid=$(sha256sum "$MANIFEST" | cut -c1-12)
    n=$(wc -l < "$MANIFEST")
    git tag -a "$name" -m "set-fingerprint: $fid | files: $n | generated by scripts/doc-fingerprint.sh"
    echo "已创建标签 $name（内嵌版本指纹 $fid，$n 个文件）。推送：git push origin $name"
    ;;
  *)
    echo "用法：doc-fingerprint.sh generate|verify|id|changes <ref>|verify-ref <ref>|tag <name>"
    exit 1
    ;;
esac
